name: build

on:
  push:
    branches:
    - main
  pull_request: { }
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: gradle
    - name: Cache Gradle build
      uses: actions/cache@v3
      with:
        path: |
          .gradle-build-cache
        key: gradle-build-cache-${{runner.os}}-${{github.ref_type}}-${{github.ref}}-${{github.head_ref}}-${{hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')}}
        restore-keys: |
          gradle-build-cache-${{runner.os}}-${{github.ref_type}}-${{github.ref}}-${{github.head_ref}}-
          gradle-build-cache-${{runner.os}}-${{github.ref_type}}-${{github.ref}}-
          gradle-build-cache-${{runner.os}}-
          gradle-build-cache-

    - name: Build
      run: |
        ./gradlew build

    - name: Run
      run: |
        ./gradlew :actions:retrieve-repository-info:v1:run

    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{ env.PUSH_BACK_TOKEN }}
        message: '[push-back] Push-back updated files during build'
