name: run

on:
  push:
    branches:
    - main
  pull_request: { }
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
        cache: gradle
    - name: Run
      run: |
        ./gradlew :actions:retrieve-repository-info:v1:run
