name: 'Test'

on:
  push:
    branches:
    - '**'
  workflow_dispatch: { }

jobs:
  codeowners-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - run: |
        echo ::debug::debug
        echo ::warning::warning
        echo -e "::error::error\n1"
