name: 'Test'

on:
  push:
    branches:
    - '**'
  workflow_dispatch: { }

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - run: |
        echo ::debug::debug
        echo ::warning::warning
        echo "::error::error%0A1"
